# Generated by Django 3.0.8 on 2020-07-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('province', models.CharField(db_index=True, max_length=10)),
                ('city', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('file_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gov', models.CharField(db_index=True, max_length=10)),
                ('title', models.CharField(db_index=True, max_length=512)),
                ('pub_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('crawl_date', models.DateTimeField(auto_now_add=True)),
                ('sub_url', models.URLField()),
                ('zupei_type', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('source', models.CharField(blank=True, max_length=128, null=True)),
                ('loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Location', verbose_name='发文部门')),
            ],
            options={
                'unique_together': {('loc', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.TextField(blank=True, null=True)),
                ('img', models.TextField(blank=True, null=True)),
                ('attachment', models.TextField(blank=True, null=True)),
                ('links', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Links')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gov', models.CharField(db_index=True, max_length=10)),
                ('target_url', models.URLField()),
                ('item_pattern', models.CharField(blank=True, max_length=128, null=True)),
                ('main_text_pattern', models.CharField(blank=True, max_length=128, null=True)),
                ('date_pattern', models.CharField(blank=True, max_length=128, null=True)),
                ('zupei_pattern', models.CharField(blank=True, max_length=128, null=True)),
                ('source_pattern', models.CharField(blank=True, max_length=128, null=True)),
                ('title_pattern', models.CharField(blank=True, max_length=128, null=True)),
                ('next_pattern', models.CharField(blank=True, max_length=128, null=True)),
                ('action_pattern', models.CharField(blank=True, max_length=512, null=True)),
                ('loc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Location', verbose_name='发文部门')),
            ],
        ),
    ]
