# Generated by Django 3.0.8 on 2020-07-29 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='file_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='links',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Config'),
        ),
        migrations.AlterField(
            model_name='config',
            name='loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Location', verbose_name='发文地区'),
        ),
        migrations.AlterField(
            model_name='links',
            name='loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Location'),
        ),
    ]
