# Generated by Django 3.0.8 on 2020-07-29 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200729_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='links',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.Links'),
        ),
    ]
