# Generated by Django 3.0.8 on 2020-08-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_config_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='target_url',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='links',
            name='sub_url',
            field=models.CharField(max_length=700),
        ),
    ]
