# Generated by Django 3.0.8 on 2020-08-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200804_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='province',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
