# Generated by Django 3.0.8 on 2020-08-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200804_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
