# Generated by Django 3.0.8 on 2020-08-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_config_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='action_pattern',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='config',
            name='target_url',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterUniqueTogether(
            name='config',
            unique_together={('target_url', 'action_pattern')},
        ),
    ]
