# Generated by Django 3.0.8 on 2020-08-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200812_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='rank',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='links',
            name='rank',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
    ]
