# Generated by Django 3.0.8 on 2020-09-07 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200815_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(default=0)),
                ('pages', models.PositiveIntegerField(default=0, verbose_name='翻页数')),
                ('counts', models.PositiveIntegerField(default=0, verbose_name='文件总数')),
                ('error_info', models.CharField(blank=True, max_length=512, null=True)),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Config')),
            ],
        ),
    ]
