# Generated by Django 3.0.8 on 2020-09-08 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='rank',
        ),
    ]
